### ISSUE TITLE
Tag won't turn red if its longer then 6 characters

### ISSUE THREAD

**Issue by JPinkney** [patrickleweryharris/major-finder#16]
Currently, the tag won't turn red when the length of the tag is strictly greater than 6 i.e. When you enter in CSC100H (Which isn't a valid class) the tag won't turn red. However when you type in less then or equal to 6 characters e.g. CSC100 it will turn red.

I'm going to look into this I was just wanted to make sure the bug was reported.

![screen shot 2016-05-24 at 4 25 38 pm](https://cloud.githubusercontent.com/assets/8839537/15518717/30cbd7e2-21cc-11e6-86ea-e6f228419abf.png)

**Comment by patrickleweryharris** [comment]
Merged
